# Generated by Django 5.2.9 on 2025-12-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_commit_sha', models.CharField(max_length=255)),
                ('commit_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('default_branch', models.CharField(max_length=255)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('process_status', models.TextField(default='Initializing...')),
                ('process_start_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'repository',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('dependency_graph', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='wiki_app.branch')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='wiki_app.folder')),
            ],
            options={
                'db_table': 'folder',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, default=list, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wiki_app.folder')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='wiki_app.repository'),
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.ManyToManyField(db_table='repository_topics', related_name='repositories', to='wiki_app.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('repository', 'last_commit_sha')},
        ),
    ]
