# Generated by Django 5.2.9 on 2025-12-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='processing_state',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], db_index=True, default='pending', max_length=20),
        ),
    ]
